name: package-publish

on: workflow_dispatch

jobs:
  package-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn 
    - run: yarn run lint
    - run: yarn run type-check
    - run: yarn run test
    - run: yarn run build
    - name: Publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        yarn npm publish --access public 
